# Предложения
## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:5001/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Очень большой дом",
  "description": "Красивый дом на берегу моря.",
  "price": 1408,
  "city": "Paris",
  "previewImage": "image.png",
  "images": ["1", "2", "3", "4", "5", "6"],
  "isPremium": true,
  "type": "house",
  "bedrooms": 2,
  "maxAdults": 4,
  "amenities": ["Towels", "Breakfast"],
  "userId": "67f4f3ae4d7b90c77bd3c3ed"
}

###

# Получить объявление по идентификатору
GET http://localhost:5001/offers/680f83b7b6123430ae0cd85b HTTP/1.1

###

## Удалить объявление по идентификатору

DELETE http://localhost:5001/offers/68152cd92b8796b5921451f1 HTTP/1.1

###

## Обновить объявление

PATCH http://localhost:5001/offers/680f83b7b6123430ae0cd85b HTTP/1.1
Content-Type: application/json

{
  "title": "Просторная квартира в центре города",
  "price": 1100,
  "amenities" : ["Air conditioning", "Baby seat"]
}

###

## Список избранных предложений
GET http://localhost:3123/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inp4Y0BtYWlsLnJ1IiwibmFtZSI6IkphY2siLCJpZCI6IjY4NDE4MWUyZmIwYTQ5NjQ0NjM2ODkyYyIsImlhdCI6MTc0OTEyODQ4NSwiZXhwIjoxNzQ5MzAxMjg1fQ.hjgIB4B9QYZ5eVKc00iBCVIR5TWgRny_PwfJkRbWx7k

###

## Добавление предложение в избранное
POST http://localhost:3123/offers/6841b7cfdeb5a80ae81ad51d/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inp4Y0BtYWlsLnJ1IiwibmFtZSI6IkphY2siLCJpZCI6IjY4NDE4MWUyZmIwYTQ5NjQ0NjM2ODkyYyIsImlhdCI6MTc0OTEyODQ4NSwiZXhwIjoxNzQ5MzAxMjg1fQ.hjgIB4B9QYZ5eVKc00iBCVIR5TWgRny_PwfJkRbWx7k

###

## Удаление предложение в избранное
DELETE http://localhost:3123/offers/6841b7cfdeb5a80ae81ad51d/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inp4Y0BtYWlsLnJ1IiwibmFtZSI6IkphY2siLCJpZCI6IjY4NDE4MWUyZmIwYTQ5NjQ0NjM2ODkyYyIsImlhdCI6MTc0OTEyODQ4NSwiZXhwIjoxNzQ5MzAxMjg1fQ.hjgIB4B9QYZ5eVKc00iBCVIR5TWgRny_PwfJkRbWx7k

###

## Список объявлений из определенного города

GET http://localhost:5001/offers/Paris/premium HTTP/1.1

###

## Список комментариев к объявлению
GET http://localhost:5001/offers/680f83b7b6123430ae0cd85b/comments HTTP/1.1

###

## Загрузить изображение для объявления
POST http://localhost:3123/offers/68429ac0e9a99fea8f6fab42/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjgyOTkzNzUyYjU5ZjUwYjU4ZWEzY2ZmIiwiaWF0IjoxNzQ5MDI0Nzk4LCJleHAiOjE3NDkxOTc1OTh9.n_VeFc9Iq4IBRNV2hANXo2eWCV9Ztb8MrLy58f_pF54
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< /Users/User/Desktop/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###
